/**
 * 세계 육지 윤곽과 국경. Natural Earth 1:110m 자료(공공 도메인)를 줄여 담았다.
 *
 * 손으로 적은 좌표가 아니라 scripts/make-worldmap.js 가 만들어 낸 것이다.
 * 고쳐야 할 일이 있으면 그 스크립트를 고치고 `node scripts/make-worldmap.js` 를 다시 돌린다.
 *
 * 육지 고리 109개(점 2373개), 국경 302줄(점 1440개),
 * 0.1도(적도에서 11km) 격자. 세계지도 한 장에서 1픽셀도 안 되는 크기다.
 * 국경은 두 나라가 맞댄 선만 담았다. 바닷가는 육지 윤곽이 이미 그리기 때문이다.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.CrewCal = root.CrewCal || {};
    root.CrewCal.worldmap = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var PACKED = [
    "cj@noBb@eBJ@DMODBu@Pg@Jr@P@BFKz@IB?j@EHGCBVHIFJ?_`FFr@^g@LBCb@NhAb@bAMZNr@GHHPCZ`@\\FABUZ@@RNFFGJ`@TFB\\TDPZwAZ[ISQE_@{@iB]O@VPJTr@YNFr@^p@LODhAM?C\\HXB|BtAlC@_@N]IK@UT[PARNv@Hh@d@x@`AJZIVZl@RDTj@J@JSb@U`@FLr@m@FCOOLG\\]KERR~@]UIJ^r@@RHHN[H?BOMUF_@JABZb@d@HSt@a@N?BJPO^F@JfAn@`@v@J`@EFTz@TF?HU?EZd@r@LBjA_Ad@G`@@|@nAKFMEM^_@PGb@OC?PrAP?Mb@Kd@q@rAW@L_@h@iAXe@^JBgAImB^Vb@EVk@A]JSXi@R?PRBEXF@Bd@N?HHLZp@x@F?Ld@lBF@JNFDEDPPNQPmC|@kBPHh@WXGGEDUd@]RD`BKpAYFAHJb@[~@k@Z@h@l@OR[d@KWCBKVBJGAk@m@o@j@GJe@XUd@XBLX@Xn@F?Nx@NB^dAL|@JJ@\\s@P_@Au@b@c@b@o@JKRkAn@?H[Ed@Rm@\\jAa@j@_@NBT[bAKJQh@QdAoALJXe@_@aCZ@jA\\r@b@fCrCh@Tb@FDK`@Bl@YlAEf@XPh@j@r@L@^Qf@@^x@HEr@LnAnATn@?~@Pz@QZYDQE{Az@cBPoAp@m@?m@M]UYA]NKEgAXmA|@sASKFUPHr@g@^Bn@ZlAIr@Px@I\\q@bAgAn@Yb@[@UP[Ug@GkAPs@e@c@Ma@c@AQc@i@YB[I]o@a@SJiA[iAEiCIUBMH?CQHHLEP@HJHA\\aBPITcAMSW?K[d@sCMi@LSGCD_@IO}@[WAIDGGA\\JL@\\INHf@Kh@]XOIIJQUA]MG@e@Qo@?a@T}@Ai@SYKBs@~AS]GHM[RpAJ?B]FBLn@CJGCERKUCDC^G?@R^T@Nl@T\\U@VNVKDAVBVJM@HEXTOBFNSH?CPHE@JPG?LGN]Jg@`@[Ac@dA_@TAJFDO@ANDNXEh@q@?OH?Xs@FBKZJFFMH@PR@FUGSLa@`AW^SDIXXn@Ed@D\\V@Pj@`@TJGf@j@?l@NRST?n@[AGLi@Mk@JM[DyBKIg@C_@b@G\\M@@{@WDHQOm@OEMk@]QGcAIM]L_@GKi@NDFKRXPEBSF?I_@L_@UeAHi@ICE[_@BKIGQNO?O[ECRK@E}AIUIRLfBQ^SCQFKGe@mAG@IZD`@LRJC`@fAZLVa@TPDTr@PAVNJ?VqAp@Vf@BXIZcALKQe@{AaAuAg@wAGkAO]CiAL}@DXJUESNwA^{AL?Nt@KfBL_@\\AHi@GAIJEMJo@EOMJSm@Fe@MIKNKIKLFw@HI@VJ?DMC_@KC[oB@OJRMiBJUKWKTGKFy@ZcBIMOTAVGGUJQc@QM?cAJCNRRSZBJUh@n@@U_@u@IJMGATIBSOOXMc@MBHSRF@UMHGa@?i@Jc@QPS@E}BKNKWQwB@eAIqAQWGo@Da@DZ@m@HCCmAP{@HBTxABgALIIi@NwCMA@iAJ_@JIFJVw@SSF_@AwBQNG[JsDZeAAwBFON@DWCiCPc@EWMNGILaDFb_F",
    "jInoBBs_FBLG@COGn_FJB",
    "|s@noBKQFc@G[F]KwAL{@NqDEy@HeCKkBGCEnCKdAWQIBQlAB{BSsAQ|@ErBUv@UDF[@qBQgBOFEECYDKWuDBuHOsBR_@ESNiA@kCGIMVAV]VD{ALw@E{BMQPoAFiAOWPqASqCSc@m@ZWQW@GGm@uAYgBBKPb@Fz@LJLID^\\f@Vq@\\[z@S^fAXzB@bCVeAHrAN@Ts@h@yHN]]gDFkCMg@UsFSTBtBWB_@iCK_CScBKc@GECTOUM}@Ug@Fy@OIJs@EgAFIa@}C@c@NYOs@Fa@IsABk@JUCyAOaBWe@X}AWcAQkBe@mCBe@Xm@Lu@Ku@H_BXOH@Jb@FA?WVVFg@CUk@y@GiAW]UiAAoAQWPa@DyBCmA_@}@XcACoAOcANg@JsAOcADoBKwBQE\\]BQA_DRUHk@HiAEc@RaBRo@BqBPmAf@d@L~@b@p@P@TW@e@HGFfB`@f@\\mAPgBHIJkA@eBB|~E",
    "mj@pw@R?OYLWLDLS_@a@UABy@HYHAJNHMH@Ld@Cp@b@\\LV@ZFNJ@BTNXTRf@H@]`@QC[f@uBBu@b@CTMR]EOUI]HKLG_@[a@_@NMVUWo@NAuAXo@?c@h@EN_@K]]_@`A_ALF`@yANGHUVAd@tA?~BbA|A]o@QgAHQJPd@KHYCa@USL?FMn@nBALQ@Oc@Bt@DAT|@LJL@LOLhA?c@@h@d@PKJTGVNMCWLRAALDMl@Kh@bAh@j@Z?|@W`@D?NMHg@VW?SVHROX@v@@FPGBRKZ?j@Zv@PN\\EdAN|@_@Ve@Ko@KWa@II_ALEp@RCHf@@JHAmAL_@RC~@Jh@_@BOOc@Rw@OUWCIKA]W_@DMLNl@COMUFGWOE^a@?g@HYIKAo@DNHEH_@NAJ_@VKN[B}@^u@l@OBILANNDE@c@R?KORy@HIJBEWHcAd@w@D_@j@Q`@FpAfA~AJnA^TTFr@\\z@RPv@FpB`BJTAXSj@H@PYLBFMH@XPH\\@|@d@CDJ@n@RADMGIJEP`@\\FJ`@LDPg@PFJVVJNX`@QAXJXPB]lAgALc@]E\\OQa@EFWi@IELXDCJmAUi@FAG}Ac@eA@YK{CM]BQTw@xAsCjAU\\GGSHg@_@IBHFIJUAe@OKWWIWYEFs@?OLO?KZNPJIDPKBKn@M@SZH@EJW?c@f@GCKhAm@dAHd@s@hC_@f@IBSG[Lw@`AO?OTMBU^k@PK`@^AdA}@n@QTYFJe@j@Y@a@v@?IQGSXcAb@SVKh@qBjAq@@u@Ku@NB_@PIe@Bc@zAQJKCIXOBe@t@QBOXQJAp@Y`A[nCBTLCNhA]EEUEDd@bAHMNPLh@Zh@^~B_AmCYMHh@MXF^QACd@M\\K@GL_@]?]Mm@KLGMFrAEZS`@QgA?OH@?i@m@dBIKI{@QYUiBLm@HuEXmCMi@@]M}@FMMSRm@M[NAGw@ZwCHZAkBJSIUGRGKAi@Nc@Fw@C}@KBCQF_@P?OK?OSISl@UAMWJm@T[HPBe@",
    "es@|ON}BH|EFmCEe@FOHTMsCB{@FKTzC@m@Xf@V?JWF~@He@PC?TPY@j@FWDFBv@LYF?Ap@Nu@NEB`@Qf@JEJV@qA^jBFpAZn@VnBLPXHN^NGb@R@ZQ\\?f@u@`A_@LQZMGGLWSE]WKJr@EVWEB{@Qr@Cb@QUi@r@GXG?Kt@?nCQx@G{AK`CGASuCGGEt@WsBIFGkBDsAIs@LuBIn@GAQcD?eF",
    "rGwxALEEMNOnASZo@d@Q@STCb@g@NCf@Iv@H~Av@`@DF`@Vf@KZIAPZOz@e@RI\\WALHBPa@UM@f@b@GNe@PUz@LfBNd@PH@jATd@AZO^K?EMa@?mBn@FIQFLOe@Ns@MLAMGUi@SsA]YQAQMPGCIIFIEBIMA[YG[TY@WKBe@WGg@I?ENCKTy@EWHIPR`@Ht@}AEMSGoAGa@O|@U",
    "}r@xi@HcCTrB?k@`@pBHpB@[BLHOXvAFe@Jt@EpDI@Cc@MHFaAQz@Qy@Sb@CeB?rB[nAOyBFm@KOC}@?wE",
    "wl@bu@LOOQIs@Ta@JBM{@RgAHAEe@LSFo@Xc@Hb@PmAP]?]LDV`@[v@@XJ@Xw@RKLDSjAb@s@S~AIVEESx@Hx@GPMMCmAED]_@GBWnACMUv@Hl@EfAGjAGNGS?ZSDQOMgAJN",
    "VyrA^EJUUOKg@j@}B^[J_@HE@PLC~@eAIv@g@d@IXJZNADNC^OPCRD\\UUe@Ne@rAJLOBINKa@?\\Y`@Ie@Na@",
    "ul@jfAFHEm@HYIWXa@GISL?e@FU`@QReAF@@^FKDDGfALpCIJCj@OVGaBAlBGHGm@E`AU]Ku@BS",
    "ek@}b@AjAGDEb@I@CSK@Og@CPOo@IDa@sEAg@FMj@nEd@|@PCNe@",
    "eo@dz@D}@DQFDHc@AaDNYHh@A|CEr@UHGRI~@GG@g@",
    "nGi^h@E?LVA~Ct@L`@KZy@Lg@Uu@FWGGe@W[QC@Gc@Q^Q",
    "eVcwAf@LH|@TZELO?LpANS^LHJGHQCSRi@_AA}@c@SHM[g@WMWBKGCUj@IRPT?",
    "sn@rbAFGCe@HCHJJtBE`@Ii@?tBYm@R}BQZGQ@SHG",
    "tBcaA?Ta@h@wA`A_@LiA`ADk@|@}@?Uf@i@NFFSVINWv@D",
    "yp@mJL_AFp@b@d@?VKh@EQWdAONGcCFY",
    "c@uhAPU@V^DLPp@HE@FTKFGVFVIFA\\Y@URc@?MK@]OCG_@kAiA\\q@j@d@PMH@",
    "yp@ju@FWR~@@b@Ah@ITKQ?d@O`@Oo@CFAm@R{AJO",
    "vo@f[HY\\KRnCGhAGCK{@_@m@?eA",
    "gMxp@D[b@s@F]FfAIMERQJOdACGL~@Yu@Fs@",
    "qh@`HLBLULXPjAIpAGSIj@Ic@Ch@MKA_@L]K]DYI_@?a@",
    "sk@hjAHr@Sv@c@g@KR@qCLi@RhALXF?",
    "fC{bA@e@GEd@aBFTS|BQx@SM@WNY",
    "yXu]RY@NZLVEL_@A{@g@AENME?LQCAc@URBNN@a@DEV]R@SM?Aa@_@?Ab@Jh@b@n@PQL@`@_@",
    "gq@{NDg@J\\@x@Cx@Mt@A_D",
    "r`@ji@Pu@HFE\\LTATS|@a@n@XgAWOGS@MVO",
    "ip@m}@A`BYjAS}A\\uAPD",
    "sc@z@RTAi@`@T@SXS@M^QBWPLHGHP@dALj@CJWo@Kd@EUIJMC@]KCKLCVSBHJ]Jc@W?g@",
    "u^wxA`@UE\\ZJTQL?KNLJcBAQJ[AIQGFCIhAQ",
    "gn@uyANNBhBMf@KICYH}B",
    "pXckBFCGOFCh@\\HGD^`@PLXGr@UEi@eAg@_@IMFC",
    "rUclBRMMATKDOCa@\\HANj@VFNGHOIKDGTMO[Ay@h@Na@PE",
    "ah@ft@HC\\aBDPMh@Rn@IF@XIOa@I?M",
    "[gmARNBL?dALBPQOo@H?CHRXbAa@DJEFOI@VGAKLSADLr@AARe@AMLcAWMQFg@Im@",
    "~p@fd@RJAtAKb@@wAOYFS",
    "iq@}^HdACTGK?l@AeCBF",
    "oo@rgAL@FNJvACZ[kAAy@",
    "u^`b@PLEMBKDDFm@LDCMVINHATS?PV?JIMCR?z@MICFk@c@Qg@PL",
    "jk@xi@VDDl@?XGIDl@MNIy@a@GK[h@c@",
    "mKjl@Ds@Ra@FFCf@NLKRAh@GA?i@OHAJEO",
    "|k@z|@@k@HK?zAK\\?aA",
    "qJyjA?QZEVN^?Hm@XAUVFBKLAZKGEDF@KH[BFGq@G?K",
    "cm@v}@?{@DEHRF_@PBDr@U~@E?@i@MTGU",
    "}o@u`AFpB[u@JaAFD",
    "}o@p}@FGIlBESCVG@H}AHM",
    "sZ}xABMGMTCDZRPM^TH?TSBMIAUk@KZe@",
    "ol@fy@NTATYJM]BoATt@",
    "i]dlAEj@Wn@ODHs@b@m@",
    "}n@p|@FOXH@^CTI??^M@GqA",
    "gD_nAVAPDSFHFV?KVW?GJP\\EBOGMWHEOa@O@HOPC",
    "}m@e}AFTIdAEEFuA",
    "ul@tn@F~@KZII@m@Jc@",
    "tp@nbB@d@Sr@GKBe@Tg@",
    "u_@fCJb@AZUOSHY{@JSl@T",
    "ej@vz@DLKdAM_@Rs@",
    "lB_~ANb@Kd@C]IEHA?KMOK@@OVD",
    "uo@mNHj@Eb@CMGJCi@Jc@",
    "|l@vjA?q@J\\Gn@GCBW",
    "hEwlA@PQIKUEk@Rj@LL",
    "{Bwq@BPOF[B_@Gl@a@XJ",
    "wl@wxAChAIk@L]",
    "qo@zcADd@EZEgADD",
    "nX{yADSCe@l@FEDLLAPm@XI?@M",
    "|^pc@FOFDDZGFHPIHMu@",
    "gMwjANH_@Ja@[DIj@N",
    "|l@nmAF_@G`A?a@",
    "{m@ny@FJEr@Me@JY",
    "{VuH^FSt@ICAy@",
    "zLmgBBFMV_@\\h@}@",
    "yo@zz@?l@OHH{@DB",
    "UmoAN@AHX?e@LWITO",
    "{f@hjBH{@DNEh@I@",
    "yDaiAPX{@m@NCXV",
    "`DykAJ@@x@KODKG_@",
    "|@qpANEIx@KCDo@",
    "cp@pcABv@ISDc@",
    "iUyMFs@F^GVGC",
    "ub@r~AFROLI]FUHP",
    "xAu~ADDSFU`@CCLYXQ",
    "{l@h`AJPM\\@o@",
    "sFmmAVEENPEDH[H@KG?OJFW",
    "uk@noBBo@Hn@M?",
    "`DuhAJWDn@QW",
    "uJ}cAHNENQ@Mk@FCRL",
    "a\\xf@@a@FPM\\EGHE",
    "iUsTT^ILKm@",
    "wXwDLKX@DPi@JCS",
    "iTcsAPFEFNNEJUI?a@",
    "mEolAXRMJWI?KJBQOP@",
    "eJ`o@EZC[HM?L",
    "}h@ln@?TIBIG@a@PN",
    "ef@dr@HVEPGOBY",
    "w`@|qAASTFNQWd@O@BI",
    "md@nfBEd@Ac@FA",
    "wa@}FNJSVE]HE",
    "`^}j@@^WCH_@JB",
    "jEmjAK`@CQNO",
    "fCm`BEL[L`@[",
    "kJ~g@D^I?B_@",
    "kY_ENFQLMQNC",
    "mFekADWVT]@",
    "zBesALH]ENC",
    "{Mlo@OPKCZM",
    "eG}jAPBYRFW",
    "dAonADDKPDW",
    "}Jd`B?FW?NUFL",
    "xIonBPC?VOEAM",
    "dEqcBARKBLW"
  ];

  var BORDERS = [
    "e[|h@KL[?EZd@\\HN?bAZd@?d@@HJEVjAGF]Sa@H_@l@[dAB~@Kt@MHFF?fP",
    "_\\u]CHIAKJ?NMNi@UJSMAUi@?]TcAGUHw@Ea@IEM^Sa@MLEGGkASmABc@TE@m@H@SeADFNYp@k@IKJYE]Zi@AYJK",
    "e^}gAb@VFCGo@Ta@D@?l@d@lAE^JJNINZXjBUrA?xA]RUvAGDWGOLQl@MB",
    "t_@zi@E`AYFERU@UU_AKCIKJGE]LCI_AEEKe@DMMc@Kw@Ly@O_@[o@@IUYC",
    "e^}gAEl@ThACj@S^B~@GZOBM~@RTJGLPUdB\\vA",
    "eOt{@Id@{@f@G\\NJENq@r@HxA[hABn@",
    "oYspAI??Ii@@Ai@cAe@LnAQFMVG`@{@b@Ml@Br@HNDIH?d@ZJZGV",
    "mYkk@^t@GDAXOB?HSAMVBx@i@dAJr@hAA",
    "ga@ppAUIM`@c@`@[h@Pf@U\\Ef@{D?",
    "sQae@H_@KkA[KKo@K?QSKF?SWMQDSmA",
    "rKjc@g@MQNSA?f@q@DYjAQTc@A@XT`@?V",
    "wLsN?mF",
    "yMsi@MK?k@i@NGLUU@W}@s@M?KQIN]NGI?u@OQ",
    "xE}MB`@kAHG^DLNF@\\k@VBnA",
    "xIiFEc@FKAsAHM@o@Gc@",
    "kVqh@K?Ql@Wb@SHAZSHKZR`@HC?T",
    "yF{GUTJNGXJf@IVBROZFXb@H",
    "kFpk@X^XF@Ih@O?e@PM?i@^HVIHH\\Q",
    "eEs|@g@Se@HYPUMk@\\YQMc@",
    "cHrFOIA{B}DR?_@",
    "ej@{K?JL@Cd@JD?P~@~@FEFDARRLXAHKVDVX",
    "mDgT_@DGH]??HBJPEXRIZPRAj@QR@LZJDJFM",
    "aGaHGAAJSHYIQWkAMQN_@B",
    "wLsN_DD_@I",
    "nNmKTQPAAM[a@FQC]e@[]m@",
    "oYeq@IVG`BNLE`@HN",
    "eIwYYKLgAa@i@Gy@",
    "sN`BhB_DJAAU",
    "iMiHISjA}C",
    "eAqJM?OSRy@MGG_@A{@",
    "yd@qPo@cAM\\KGMPQMUTOQM^MC",
    "~AcGEUHI][c@GYWmAQ",
    "}EiM]J?F}@U@QoA@",
    "cPlD\\??`Ap@A@Rf@??lADD",
    "ej@{PMGGXF\\V\\OdADJ",
    "kLrIAk@k@QU[i@UCs@KA",
    "m\\{VMKAQa@GS|AKFANICIJBf@",
    "aM{~@`@S?WPGJPJWv@k@`@A",
    "q_@{R@PLDKhBDb@",
    "g@qcAVOMo@DQCOy@YBg@",
    "zLdf@`@e@X{@FC\\RDy@OQQC",
    "{Quq@ZRZ_AR_B]?",
    "_KuAuAyC",
    "yF{GPCNNjAd@FJGRJP^L",
    "}EiMHVTLHj@TNHt@",
    "iPlDU?WeAQ]MAMm@y@P",
    "w]su@L^R@HHEf@b@LJp@`@QDLHA",
    "eQc\\Ad@g@v@St@",
    "gUge@Q@]jA?b@N^",
    "gV_[\\Y`@LRMHWNIL@TQ",
    "eVki@A[Y_@BI^IO]@a@",
    "nNmK{@??SeA?Gm@FGK]",
    "{Quq@@Wd@eADm@",
    "uPy{@?KNO^?NRV@CURCBKNDHWCMFA",
    "}Q}DXGp@BFF`@SCITW",
    "dDeR@`@NJr@?FWTAAN_@`@BZQd@",
    "zElj@?R]?JNKd@IC]RQQYCSi@?Q",
    "tH}QF?Nq@fA@f@\\",
    "}Q}Dc@FW\\gAO",
    "~Inj@UK]Do@K_@N",
    "|IoM[X_A??i@g@@",
    "oYeq@Vh@@XLF?`@RT",
    "mBaUTQNe@B]QWFU",
    "tDcwAaC?",
    "eY_\\KPQlB",
    "}WulAe@s@DYI@G]KGJK",
    "tAtj@_AI_@JAMGAAJK?Em@LK",
    "nA}EKOKFGSIAJ[IE[?KHWIARSB",
    "wL}x@EIc@ABOOIe@IMYBMWC",
    "kUqUSK@w@Iw@",
    "wKq}@PI?Mf@BOi@@ONMRANOXF",
    "Yxh@JKAOMYMOEPY@EFDa@Mi@ME",
    "mAeYUc@?Y{@w@",
    "yFoYg@n@?\\IJNDCV",
    "iZ{PIZH^At@GB",
    "aM{~@Q}@J[J@FGBS",
    "sQae@QQM@AN]Fs@M",
    "iHGA\\\\f@?Pb@VXB",
    "lEeXXv@Ax@",
    "_HwUb@Hf@^d@D",
    "kPix@]y@DOIMLIFF@U",
    "`@_YOJiA?UQ",
    "`Oba@a@E?T_@FEh@e@D",
    "Bbn@Ta@RK?m@FORLJO",
    "_b@eLGkAN_@",
    "sCqH[DMRIC?Yy@R",
    "iFgA^A^Rj@?",
    "gUge@Bc@Q]OCKSDO",
    "eUso@VUXEH?ALTCXo@",
    "ReTh@kAJAR[",
    "~Inj@b@WRFp@SCM",
    "dFsTh@?RUXAPNKJ_@AKX",
    "yEwYDBZUVqA",
    "ReTU?c@Uo@R",
    "eYrDGMHEAYHEDHZB@F\\IRH",
    "sCqHVN\\?n@]",
    "a]sIDQOy@BY",
    "uBUeBT",
    "bAdq@R@JWg@[GWSU[A",
    "`JyNBa@e@e@I[",
    "qY{@At@Oj@",
    "yBe@{@B[PIA",
    "eAgRV?@G^Xd@D",
    "uNme@UGK[]J]b@",
    "vDoSXM~@NDI",
    "`Oba@CIJIN?`AnA",
    "cBx@YDe@K[B",
    "wL}x@_@JJFIH]WEp@M@GVJFJMLNDKh@E",
    "q_@{RSHE[[d@OAKt@",
    "rKjc@OPBt@r@P",
    "dM|h@QODYLKOGBY",
    "zQ~b@AKd@_ALKHFJC",
    "xLkQKZSDW\\_@P",
    "aIhIIe@f@o@",
    "zPeIIILKBUI[iA?",
    "cSoWLj@RSHHNZCT",
    "_KuAl@?XLL~@",
    "cXkk@@ZJ@@sA",
    "gB|d@BMRIVHRGHUKg@",
    "cGpu@c@o@Cc@",
    "wBtb@d@Pj@]",
    "u\\_E?aAO?KM",
    "c]sOH`@Cj@",
    "{SgWSk@g@EOS",
    "dDeRc@Tg@D",
    "}]yJ_@lA",
    "cXkk@EHICDZVNANHDBOLCTJ",
    "cPlDn@kA",
    "{GcbAd@AL`@JGHd@",
    "{Jo_@S{@g@MMH",
    "u]cMGhA",
    "zQ~b@hAN",
    "eMoa@E~@WF",
    "i\\oEF?@VFB?j@",
    "|LoRh@MZ@",
    "gJ_WR\\r@H",
    "T_RAeA",
    "Bbn@KP?TS\\",
    "kE~Ci@THTEXE?",
    "yX_b@Sd@H^",
    "gBcPNKCa@TU",
    "sBv`@PHXIXH",
    "_D{\\]Ue@?",
    "a\\sGK^Bb@",
    "q]oGDcA",
    "wAxCYAORWC",
    "m[sPQMES[VAh@",
    "cJtv@?d@H??HVS?V^H",
    "a[{JEz@FDj@y@",
    "ej@{KVy@d@G",
    "aPov@JQAm@SD",
    "mBaUa@VKTQS",
    "eAgREs@IK",
    "gDjd@JNNEDPLBNM",
    "cYiOH??|@",
    "}^q@^_A",
    "u`@uMGg@QUG@",
    "}`@eMAz@",
    "mSiUFUUg@",
    "vGwSNz@LA",
    "gDjE_@PBXPN",
    "gGnIE{@GXD^",
    "cDkNz@w@",
    "mFk@M?EVg@J",
    "{FpGBz@",
    "cc@eND{@",
    "_Ev@[@?y@",
    "m@_IJ@Kv@",
    "cDkNOTUASL",
    "aPov@SWHa@",
    "sFc_AWDOMAk@",
    "m@`a@B_@i@W",
    "uMoFRi@GO",
    "m[qG?_@MIEO",
    "a_@aACa@LW",
    "uSeFL@R\\PABH",
    "}^kHNv@Z[",
    "m[sPY@[\\",
    "eV_n@VSF_@",
    "w^{BUBEOYA",
    "}^kHu@P",
    "mYkk@@ELPJu@NXAN",
    "oEjBBr@",
    "oEjBNU?]",
    "gV_[k@LEM",
    "yCfDQKWHGE",
    "ej@{PIq@",
    "u]cMG@Q[WF",
    "}\\eM^`@BN",
    "sZeMG?CTYZ",
    "wXc[RQDDFQL?",
    "eAqJCZZT",
    "gVmY?q@",
    "gK{MG??Wg@?",
    "i\\cIFn@",
    "gWa\\O_@DEHFHQ",
    "mIe`@m@T",
    "g_@uMQDCKWD",
    "bQcQAPRTJUWWED",
    "w[gCLEDFLEBKFB",
    "dFsTi@PCP",
    "u[wJKj@",
    "ha@zh@?^m@?",
    "qNgb@?HNABHVD",
    "wFdFCj@",
    "cYk]JNMZ",
    "cHrFj@M",
    "cWgoAPj@",
    "}Gw`AFOMIFQ",
    "u\\_EAh@",
    "xAiQU]SD",
    "{By~@HPI@ER",
    "}Ept@Bg@",
    "}X_YFg@",
    "vDoSQh@",
    "e@hb@@IM?B]",
    "sWam@PC@SRA",
    "}b@aPEGQDOK",
    "uRcUf@H",
    "oXcLIg@",
    "cJtv@d@C",
    "mY_MQKGHKC",
    "}]{BHe@ZJ",
    "k]sIQe@",
    "gYoPBd@",
    "|IoMBe@",
    "{Pg]Ib@",
    "m@eG?b@",
    "S}DAc@W?",
    "yCfDFNWJ@F",
    "xLkQBc@",
    "mQyTa@J",
    "wa@qOKa@",
    "iKxk@`@?",
    "v@cQ`@E",
    "w\\uC@NNLF?AIFE",
    "m@aF?`@",
    "gCbF_@W",
    "yFoYPLHABS",
    "w[{SD_@",
    "kGzu@I@I\\",
    "bO{RANRDJKKO",
    "{ElHO[O?",
    "wXc[@]O@",
    "kYoLICKRHH",
    "XoQ\\J",
    "oa@iLD]J@",
    "mFk@EKHO",
    "oCto@MMOB",
    "v@cQG]",
    "yAkfAHIEKUC",
    "eQc\\SM@M",
    "ka@iD?[",
    "uXgZA[",
    "y[sKBZ",
    "yW_[KTO@",
    "ma@vCR?B[",
    "i[oQCZ",
    "}Kwx@YE",
    "sToUFKPN",
    "yW_[RY",
    "eWy[OFCP",
    "cDzr@YAAG",
    "a[{JPKHF",
    "eVki@EX",
    "cb@sPYP",
    "_Hzv@YW",
    "uAgTWY",
    "kLg~@BKU@CI",
    "n@aRMEKF",
    "a]sIF@?JN@",
    "{EQQY",
    "}TgT?X",
    "{SgWVG",
    "wWsKWO",
    "gSeUADTDAI",
    "~AcGGFJL",
    "wKq}@SU",
    "u[wJLKDF",
    "wYuKMT",
    "eY{KTG",
    "rBsFSO",
    "cYiOBINH",
    "eY{KES",
    "yXkMSJ",
    "i\\oECPGA",
    "a\\sGPA",
    "gSeUP@",
    "tOaSQD",
    "{E??Q",
    "eZ_KPJ",
    "qJdv@LN",
    "T_RBN",
    "eYcKOE@G",
    "kYoLAO",
    "mPav@CKNA",
    "lJ~j@MO",
    "tOaS?M",
    "}`@eMFO",
    "qGhw@MM",
    "sYqKLI",
    "}F}YBL"
  ];

  var cache = null;
  var borderCache = null;

  /** 눌러 담은 글을 좌표로 푼다. 처음 부를 때 한 번만 푼다. */
  function decode(line) {
    var points = [];
    var lat = 0, lon = 0, i = 0;
    while (i < line.length) {
      var shift = 0, result = 0, byte;
      do {
        byte = line.charCodeAt(i++) - 63;
        result |= (byte & 0x1f) << shift;
        shift += 5;
      } while (byte >= 0x20);
      lat += (result & 1) ? ~(result >> 1) : (result >> 1);

      shift = 0; result = 0;
      do {
        byte = line.charCodeAt(i++) - 63;
        result |= (byte & 0x1f) << shift;
        shift += 5;
      } while (byte >= 0x20);
      lon += (result & 1) ? ~(result >> 1) : (result >> 1);

      points.push({ lat: lat / 10, lon: lon / 10 });
    }
    return points;
  }

  /** 육지 고리 목록. 큰 것부터 온다. */
  function rings() {
    if (!cache) cache = PACKED.map(decode);
    return cache;
  }

  /** 국경 선 목록. 고리가 아니라 열린 선이라 이어 그리기만 한다. */
  function borders() {
    if (!borderCache) borderCache = BORDERS.map(decode);
    return borderCache;
  }

  return {
    rings: rings,
    borders: borders,
    count: PACKED.length,
    borderCount: BORDERS.length
  };
});
